name: Make a Release
description: Make a ZIP-file of some folder and upload it to GitHub
inputs:
  folder:
    description: folder to make archive from
    required: true
  release-name:
    description: Name of release
    required: false
    default: ${{ github.event.repository.name }}
  github-token:
    description: GitHub token required to tag and deploy the release
    required: true
outputs:
  release-archive:
    description: Name of release archive
    value: ${{ env.release-archive }}
runs:
  using: "composite"
  steps:
    - name: Make release zip file
      run: |
        echo "release-archive=${{ inputs.release-name }}-${{ env.build_version }}.zip" >> $GITHUB_ENV
        (cd ${{ inputs.folder }}/; zip -r "../${{ env.release-archive }}" .)
      shell: bash
    - name: Upload Release
      uses: ncipollo/release-action@v1
      with:
        tag: ${{ inputs.release-tag }}
        artifacts: ${{ env.release-archive }}
        token: ${{ inputs.github-token }}
