name: Make a Release
description: Make a ZIP-file of some folder and upload it to GitHub
inputs:
  folder:
    description: folder to make archive from
    required: true
  name:
    description: Name of release
    required: false
    default: ${{ github.event.repository.name }}
  github-token:
    description: GitHub token required to tag and deploy the release. It's optional if don't need to deploy to GitHub (deploy-to-github=='no')
    required: false
    default: ""
  deploy-to-github:
    description: Deploy release to Github
    required: false
    default: "yes"
outputs:
  release-archive:
    description: Name of release archive
    value: ${{ env.release_archive }}
runs:
  using: "composite"
  steps:
    - name: Set up archive name
      run: |
        echo "release_archive=${{ inputs.name }}-${{ env.build_version }}.zip" >> $GITHUB_ENV
      shell: bash
    - name: Make release zip file
      run: |
        tmp_cwd=$(pwd)
        cd ${{ inputs.folder }}
        zip -r $tmp_cwd/${{ env.release_archive }} .
      shell: bash
    - name: Upload Release
      if: inputs.deploy-to-github == 'yes'
      uses: ncipollo/release-action@v1
      with:
        tag: ${{ env.build_version }}
        artifacts: ${{ env.release_archive }}
        token: ${{ inputs.github-token }}
