name: Publish to ECR
description: Build docker image and publish it to ECR
inputs:
#  ecr-repository:
#    description: Name of ECR repository to publish
#    required: false
#    default: ${{ env.ecr_repository }}
#  build-version:
#    description: Build version
#    required: false
#    default: ${{ env.build_version }}
  access-key:
    description: AWS Access Key
    required: true
  secret:
    description: AWS Secret
    required: true
  region:
    description: AWS Region
    required: false
    default: eu-west-2
  build-args:
    description: Values for --build-arg docker option
    required: false
    default: ""
outputs:
  image:
    description: Docker image
    value: ${{ steps.docker.outputs.image }}
runs:
  using: "composite"
  steps:
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ inputs.access-key }}
        aws-secret-access-key: ${{ inputs-secret }}
        aws-region: ${{ inputs.region }}

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build, tag, and push image to Amazon ECR
      id: docker
      env:
        DOCKER_BUILDKIT: '1'
      run: |
        echo "::set-output name=image::${{ steps.login-ecr.outputs.registry }}/${{ inputs.ecr-repository }}:${{ inputs.build-version }}
        docker build ${{ inputs.build-args }} -t ${{ steps.docker.outputs.image }} .
        docker push ${{ steps.docker.outputs.image }}
      shell: bash
