name: Build and publish to Chart Museum
description: Build a package and publish it to Chart Museum
inputs:
  name:
    description: Name of project to build
    required: false
    default: ${{ github.event.repository.name }}
  build-version:
    description: Build version
    required: false
    default: ${{ env.build-version }}
  chart-version:
    description: Generated Chart version
    required: false
    default: ${{ inputs.build-version }}-chart
  chartmuseum-url:
    description: URL of Chart Museum
    required: false
    default: https://chartmuseum.riskfintech.co.uk
  chartmuseum-username:
    description: User name for Chart Museum
    required: false
    default: ${{ secrets.CHARTMUSEUM_USERNAME }}
  chartmuseum-password:
    description: Password for Chart Museum
    required: false
    default: ${{ secrets.CHARTMUSEUM_PASSWORD }}
outputs:
  chart-package:
    description: Packge published to Chart Museum
    value: ${{ steps.push.outputs.chart-package }}
runs:
  using: composite
  steps:
    - name: Install Helm
      run: |
        curl https://baltocdn.com/helm/signing.asc | sudo apt-key add -
        sudo apt-get install apt-transport-https --yes
        echo "deb https://baltocdn.com/helm/stable/debian/ all main" | sudo tee /etc/apt/sources.list.d/helm-stable-debian.list
        sudo apt-get update
        sudo apt-get install helm
      shell: bash
    - name: Package Helm Chart
      run: |
        echo "chart_version=${{ inputs.chart-version }}" >> $GITHUB_ENV
        helm package chart --version ${{ inputs.chart-version }} --app-version ${{ inputs.build-version }}
        echo "Helm package created with version ${{ inputs.chart-version }}"
      shell: bash
    - name: Push Helm Chart to Chartmuseum
      id: push
      run: |
        echo "::set-output name=chart-package::${{ inputs.name }}-${{ inputs.chart-version }}.tgz"
        curl -u ${{ inputs.chartmuseum-username }}:${{ inputs.chartmuseum-password }} -F "chart=@${{ steps.push.outputs.chart-package }}" ${{inputs.chartmuseum-url}}/api/charts
      shell: bash
