name: Example of Build and Push to ECR and Chart Museum And Slack notification

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: riskfintech-ltd/actions/prepare-build@dev

      # Do some testing here or whatever you need
      # - name: Testing
      #     run: |
      #       .......

      - uses: riskfintech-ltd/actions/publish-ecr@dev
        with:
          access-key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          secret: ${{ secrets.AWS_ACCESS_SECRET }}

      - uses: riskfintech-ltd/actions/helm@dev
        with:
          chartmuseum-username: ${{ secrets.CHARTMUSEUM_USERNAME }}
          chartmuseum-password: ${{ secrets.CHARTMUSEUM_PASSWORD }}

      - uses: riskfintech-ltd/actions/slack@dev
