name: Example of Build and Push to ECR and Chart Museum And Slack notification

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: riskfintech-ltd/actions/prepare-build@44d4d5c0e42094724a18eabdf362e7f5fcfc1ac1
      # Do some testing here or whatever you need
      # - name: Testing
      #     run: |
      #       .......
      - uses: riskfintech-ltd/actions/publish-ecr@44d4d5c0e42094724a18eabdf362e7f5fcfc1ac1
      - uses: riskfintech-ltd/actions/helm@44d4d5c0e42094724a18eabdf362e7f5fcfc1ac1
      - uses: riskfintech-ltd/actions/slack@44d4d5c0e42094724a18eabdf362e7f5fcfc1ac1
