name: Example of Build and Push to ECR and Chart Museum And Slack notification

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: riskfintech-ltd/devops-actions/prepare-build@v1

      # Do some testing here or whatever you need
      # - name: Testing
      #     run: |
      #       .......

      - uses: riskfintech-ltd/devops-actions/publish-ecr@v1
        with:
          access-key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          secret: ${{ secrets.AWS_ACCESS_SECRET }}

#      - uses: riskfintech-ltd/devops-actions/helm@v1
#        with:
#          chartmuseum-url: <put your Chart Museum URL here>
#          chartmuseum-username: ${{ secrets.CHARTMUSEUM_USERNAME }}
#          chartmuseum-password: ${{ secrets.CHARTMUSEUM_PASSWORD }}

      - uses: riskfintech-ltd/devops-actions/slack@v1
        with:
          slack-webhook-url: ${{ secrets.SLACK_WEBHOOK_URL }}

      - uses: riskfintech-ltd/devops-actions/release@v3
        with:
          folder: './'
